version: '3.7'

services:
  cicd:
    build: 
      context: .
    volumes:
      - .:/app
    ports:
      - 80:80
    restart: always
    environment:  # Set environment variables here
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      REGION_NAME: ${REGION_NAME}