name: Python application test

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests
      run: |
        python -m unittest discover 

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Key Hack
      run : |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
        chmod 600 ssh_key.pem
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem admin@ec2-13-51-69-202.eu-north-1.compute.amazonaws.com "screen -S api_session -X quit"

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no -i ssh_key.pem admin@ec2-13-51-69-202.eu-north-1.compute.amazonaws.com "cd ~/fevrier && git pull origin main && docker-compose restart"